version: '3.4'
services:
  web:
    image: leprikon/web
    build: .
    depends_on:
      - memcached
    environment:
      EMAIL_HOST: smtp.savana.cz
      EMAIL_HOST_USER: leprikon@leprikon.cz
      EMAIL_HOST_PASSWORD: emailpassword
      MEMCACHED_LOCATION: memcached:11211
      SECRET_KEY: secretkey
    ports:
      - 127.0.0.1:9010:80
    volumes:
      - ./web/media:/app/htdocs/media
      - ./web/data:/app/data
    tty: true

  memcached:
    image: memcached
